# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: labeler-account
#   namespace: labeler
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: labeler-role
# rules:
#   - apiGroups: [""]
#     resources: ["nodes", "pods"]
#     verbs: ["patch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: labeler-role-binding
# subjects:
# - kind: ServiceAccount
#   name: labeler-account
#   namespace: labeler
# roleRef:
#   kind: ClusterRole
#   name: labeler-role
#   apiGroup: rbac.authorization.k8s.io
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-deployment
  namespace: recommender
  labels:
    app.kubernetes.io/name: recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: recommender
  template:
    metadata:
      name: recommender-pod
      namespace: recommender
      labels:
        app.kubernetes.io/name: recommender  
    spec:
      terminationGracePeriodSeconds: 30
      # serviceAccountName: recommender-account
      hostNetwork: True
      containers:
      - name: recommender-container
        image: tzourhs/recommender:0.9
        env:
        - name: CONFIGURATIONS_DATA_PATH
          value: "/recommender/recommender/configurations_train.ods"
        - name: INTERFERENCE_DATA_PATH
          value: "/recommender/recommender/interference_train.ods"
        - name: PORT
          value: "50051"
        args: []
        ports:
        - name: port
          containerPort: 50051
