apiVersion: v1
kind: Service
metadata:
  name: recommender-svc
  namespace: recommender
spec:
  type: NodePort
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 32700
  selector:
    app.kubernetes.io/name: recommender