apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv1
  namespace: redis
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"
