apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: profiler-client-daemonset
  namespace: profiler
  labels:
    k8s-app: profiler-client
spec:
  selector:
    matchLabels:
      name: profiler-client
  template:
    metadata:
      labels:
        name: profiler-client
    spec:
      serviceAccountName: profiler-account
      containers:
      - name: profiler-client
        image: tzourhs/profiler_client:1.5
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        - '/client/profile_gpu.sh'
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
