kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: profiler-cr
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: profiler-sa
  namespace: redis
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: profiler-crb
  namespace: redis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: profiler-cr
subjects:
  - kind: ServiceAccount
    name: profiler-sa
    namespace: redis
