// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/recom.proto

package recommender

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Index                string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_485ef8a31f14cdfe, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type Reply struct {
	Result               []float32 `protobuf:"fixed32,1,rep,packed,name=result,proto3" json:"result,omitempty"`
	Columns              []string  `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_485ef8a31f14cdfe, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetResult() []float32 {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Reply) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "recommender.Request")
	proto.RegisterType((*Reply)(nil), "recommender.Reply")
}

func init() { proto.RegisterFile("protos/recom.proto", fileDescriptor_485ef8a31f14cdfe) }

var fileDescriptor_485ef8a31f14cdfe = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd0, 0xbd, 0x8a, 0x83, 0x40,
	0x10, 0x07, 0x70, 0x56, 0x51, 0x71, 0xae, 0x1b, 0xe4, 0x58, 0xae, 0x39, 0xb1, 0xb2, 0xf2, 0xe0,
	0x52, 0xa5, 0x09, 0x81, 0x54, 0xb6, 0xfb, 0x06, 0x89, 0x8e, 0x41, 0x70, 0x77, 0xcd, 0x7e, 0x40,
	0xf2, 0x14, 0x79, 0xe5, 0x10, 0x35, 0x20, 0xa9, 0x52, 0xfe, 0x86, 0xf9, 0xf8, 0x33, 0x80, 0xa3,
	0xd1, 0x4e, 0xdb, 0x3f, 0x43, 0x8d, 0x96, 0xd5, 0x04, 0xfc, 0x9a, 0x20, 0x49, 0xb5, 0x64, 0x8a,
	0x5f, 0x48, 0x04, 0x5d, 0x3c, 0x59, 0x87, 0x19, 0x44, 0xbd, 0x6a, 0xe9, 0xca, 0x59, 0xce, 0xca,
	0x54, 0xcc, 0x28, 0xb6, 0x10, 0x09, 0x1a, 0x87, 0x1b, 0x7e, 0x43, 0x6c, 0xc8, 0xfa, 0xc1, 0x71,
	0x96, 0x87, 0x65, 0x20, 0x16, 0x21, 0x87, 0xa4, 0xd1, 0x83, 0x97, 0xca, 0xf2, 0x20, 0x0f, 0xcb,
	0x54, 0xbc, 0xf8, 0x7f, 0x67, 0xb0, 0xbe, 0x85, 0x7b, 0xc8, 0x6a, 0x39, 0x7a, 0x47, 0x07, 0xad,
	0xba, 0xfe, 0xec, 0xcd, 0xd1, 0xf5, 0x5a, 0x59, 0xcc, 0xaa, 0x55, 0x57, 0xb5, 0xc4, 0xf9, 0xc1,
	0xb7, 0xea, 0x33, 0xc3, 0x0e, 0x70, 0xde, 0x50, 0x2b, 0x47, 0xa6, 0x23, 0x43, 0xaa, 0xa1, 0xcf,
	0xe7, 0x4f, 0xf1, 0xf4, 0x81, 0xcd, 0x23, 0x00, 0x00, 0xff, 0xff, 0x74, 0x16, 0xe8, 0x14, 0x17,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecommenderClient is the client API for Recommender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecommenderClient interface {
	ImputeConfigurations(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	ImputeInterference(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type recommenderClient struct {
	cc *grpc.ClientConn
}

func NewRecommenderClient(cc *grpc.ClientConn) RecommenderClient {
	return &recommenderClient{cc}
}

func (c *recommenderClient) ImputeConfigurations(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/recommender.recommender/ImputeConfigurations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommenderClient) ImputeInterference(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/recommender.recommender/ImputeInterference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommenderServer is the server API for Recommender service.
type RecommenderServer interface {
	ImputeConfigurations(context.Context, *Request) (*Reply, error)
	ImputeInterference(context.Context, *Request) (*Reply, error)
}

// UnimplementedRecommenderServer can be embedded to have forward compatible implementations.
type UnimplementedRecommenderServer struct {
}

func (*UnimplementedRecommenderServer) ImputeConfigurations(ctx context.Context, req *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImputeConfigurations not implemented")
}
func (*UnimplementedRecommenderServer) ImputeInterference(ctx context.Context, req *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImputeInterference not implemented")
}

func RegisterRecommenderServer(s *grpc.Server, srv RecommenderServer) {
	s.RegisterService(&_Recommender_serviceDesc, srv)
}

func _Recommender_ImputeConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServer).ImputeConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recommender.recommender/ImputeConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServer).ImputeConfigurations(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Recommender_ImputeInterference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommenderServer).ImputeInterference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recommender.recommender/ImputeInterference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommenderServer).ImputeInterference(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Recommender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recommender.recommender",
	HandlerType: (*RecommenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImputeConfigurations",
			Handler:    _Recommender_ImputeConfigurations_Handler,
		},
		{
			MethodName: "ImputeInterference",
			Handler:    _Recommender_ImputeInterference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/recom.proto",
}
